Create project
ShiffaUrRehman/Backend-ProjectNinja-Express-Node pull request #3
Opened 2023-09-12 13:29 UTC by ShiffaUrRehman

2023-09-12 13:50 UTC, usamaimam1 requested changes
Please add changes and get it reviewed again after adding changes and description.

2023-09-12 13:50 UTC, usamaimam1 commented on middleware/validator.js
> +
Add a description in the schema

2023-09-12 13:50 UTC, usamaimam1 commented on model/projectModel.js
> +  },
Add 'ref' information in the model so Mongoose know that this ObjectId is referring to another model in the db.

2023-09-12 13:50 UTC, usamaimam1 commented on routes/projectRoutes.js
> +  authorizeUser,
```suggestion
  authenticateUser,
```

2023-09-12 13:50 UTC, usamaimam1 commented on routes/userRoutes.js
> +router.get("/", authorizeUser, authenticateAdmin, getUsers);
```suggestion
router.get("/", authenticateUser, authenticateAdmin, getUsers);
```

2023-09-13 10:43 UTC, usamaimam1 requested changes
Added a couple more comments to resolve.

2023-09-13 10:43 UTC, usamaimam1 commented on controller/projectController.js
> +    res.status(200).send(projects);
Why populating only username?

2023-09-13 10:43 UTC, usamaimam1 commented on controller/projectController.js
> +      status: "Onboarding",
One interesting way to do this is using a default value in db schema. When you create a new project and provide no status value, it will be set to `Onboarding`

2023-09-13 10:43 UTC, usamaimam1 commented on middleware/validator.js
> +  description: yup.string().required().max(1024),
Add a minimum condition on the project description as it can be lengthy.
```suggestion
  description: yup.string().required().min(255).optional(),
```

2023-09-13 10:43 UTC, usamaimam1 commented on model/projectModel.js
> +      maxlength: 1024,
```suggestion
      minlength: 255,
      required:false,
```

2023-09-13 10:43 UTC, usamaimam1 commented on model/projectModel.js
> +      maxlength: 1024,
```suggestion   
```

2023-09-13 10:43 UTC, usamaimam1 commented on model/projectModel.js
> +      required: true,
```suggestion
      required: true,
      defaultValue:"Onboarding",
```

2023-09-13 11:11 UTC, ShiffaUrRehman commented on controller/projectController.js
> +    res.status(200).send(projects);
We don't need passwords and other fields, role we already know, created at and updated at also not needed

2023-09-13 11:14 UTC, ShiffaUrRehman commented on controller/projectController.js
> +      status: "Onboarding",
Right

2023-09-15 12:37 UTC, usamaimam1 approved these changes
Looks good to me, feel free to merge!

2023-09-15 12:40 UTC, merged